version: '3'

services:
  fastapi_server:
    image: fastapi_server
    container_name: fastapi_server
    ports:
      - "5003:5003"

  nginx:
    image: my_nginx
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi_server
