name: flake8

on:
    pull_request

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
          architecture: x64
      - name: Install flake8
        run: pip install flake8 flake8-builtins flake8-print
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8'
