name: Test Coverage Check

on:
  pull_request:
    branches:
      - main  # Adjust to match your main branch name

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage pytest

      - name: Run unit tests with coverage
        run: |
          coverage run -m pytest
          coverage report -m --fail-under=80  # Adjust threshold as needed

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: .coverage
